import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

  // ↓ ここから追記
  manifest: '/manifest.webmanifest',   // app/manifest.js が /manifest.webmanifest で配信される
  themeColor: '#111827',
  appleWebApp: {
    capable: true,            // iOSでフルスクリーン
    title: 'LabBook',         // ホーム画面の名称（任意）
    statusBarStyle: 'default' // 'default' | 'black' | 'black-translucent'
  },
  icons: {
    // ここはブラウザ用の<link>出力。manifest側のiconsとは別系統。
    icon: [
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/icons/apple-touch-icon.png', // iOSホーム用
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


